# Generated by Django 5.2.17 on 2026-09-22 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('title', models.TextField()),
                ('category', models.CharField(choices=[('analysis', 'CMS physics analysis'), ('detector', 'Detector, trigger & instrumentation'), ('computing', 'Software & computing'), ('ml', 'ML & statistical methods'), ('pheno', 'Phenomenology & theory'), ('outreach', 'Outreach & education'), ('strategy', 'Strategy, Snowmass & community')], max_length=20)),
                ('doc_type', models.CharField(choices=[('cms_collab', 'CMS collaboration publication'), ('journal_article', 'Journal article'), ('proceedings', 'Conference proceedings'), ('report', 'Report or white paper'), ('book', 'Book'), ('magazine_article', 'Magazine article')], max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('in_preparation', 'In preparation'), ('pre_approval', 'Pre-approval'), ('approved', 'Approved'), ('cwr', 'CWR'), ('final_reading', 'Final reading'), ('pas_public', 'PAS public'), ('preprint', 'Preprint'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('published', 'Published'), ('unknown', 'Unknown')], max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal only'), ('unverified', 'Public, no identifier yet')], max_length=12)),
                ('cadi', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CADI')),
                ('arxiv', models.CharField(blank=True, max_length=30, verbose_name='arXiv')),
                ('doi', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('cds', models.CharField(blank=True, max_length=20, verbose_name='CDS record')),
                ('report_number', models.CharField(blank=True, max_length=60)),
                ('inspire_recid', models.CharField(blank=True, max_length=20, verbose_name='INSPIRE record')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('journal_ref', models.CharField(blank=True, max_length=200, verbose_name='journal reference')),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('has_other_authors', models.BooleanField(default=False, help_text="Source listed 'et al.'")),
                ('last_update', models.DateField(blank=True, null=True)),
                ('last_update_precision', models.CharField(choices=[('day', 'Day'), ('month', 'Month')], default='day', max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('review_flags', models.JSONField(blank=True, default=list)),
                ('source_section', models.CharField(blank=True, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_update', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('variants', models.JSONField(blank=True, default=list, help_text='Other spellings of the name')),
                ('in_group', models.BooleanField(blank=True, help_text='Unknown until confirmed', null=True)),
                ('inspire_id', models.CharField(blank=True, help_text='e.g. K.Pedro.1', max_length=100, verbose_name='INSPIRE ID')),
                ('orcid', models.CharField(blank=True, max_length=19, verbose_name='ORCID')),
                ('user', models.OneToOneField(blank=True, help_text='Login account, once this person uses the tool', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, help_text='Leave empty for current members', null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pubs.person')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='manual', help_text='import, manual or inspire', max_length=20)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='pubs.work')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_uncertain', models.BooleanField(default=False, help_text='Name was bracketed or incomplete in the old list')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='pubs.person')),
                ('roles', models.ManyToManyField(blank=True, to='pubs.role')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='pubs.work')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('work', 'person'), name='one_contribution_per_person')],
            },
        ),
        migrations.CreateModel(
            name='WorkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('to_be_combined', 'To be combined with'), ('submitted_together', 'Submitted together with'), ('possibly_superseded_by', 'Possibly superseded by'), ('superseded_by', 'Superseded by')], max_length=30)),
                ('from_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='pubs.work')),
                ('to_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='pubs.work')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_work', 'to_work', 'relation'), name='unique_link')],
            },
        ),
    ]
